export const CHANGE_OFFERS_STATUS = `CHANGE_OFFERS_STATUS`;
export const SET_OFFERS = `SET_OFFERS`;
export const CHANGE_OFFERS_SORT_TYPE = `CHANGE_OFFERS_SORT_TYPE`;
export const CHANGE_ACTIVE_CITY_ID = `CHANGE_ACTIVE_CITY_ID`;
export const CHANGE_OFFER_REVIEWS_STATUS = `CHANGE_OFFER_REVIEWS_STATUS`;
export const SET_OFFER_REVIEWS = `SET_OFFER_REVIEWS`;
