export const CHANGE_OFFER_REVIEWS_STATUS = `CHANGE_OFFER_REVIEWS_STATUS`;
export const SET_OFFER_REVIEWS = `SET_OFFER_REVIEWS`;
export const CHANGE_NEAR_OFFERS_STATUS = `CHANGE_NEAR_OFFERS_STATUS`;
export const SET_NEAR_OFFERS = `SET_NEAR_OFFERS`;
