export const CHANGE_OFFERS_STATUS = `CHANGE_OFFERS_STATUS`;
export const SET_OFFERS = `SET_OFFERS`;
export const CHANGE_OFFERS_SORT_TYPE = `CHANGE_OFFERS_SORT_TYPE`;

export const CHANGE_OFFER_STATUS = `CHANGE_OFFER_STATUS`;

export const CHANGE_OFFER_REVIEWS_STATUS = `CHANGE_OFFER_REVIEWS_STATUS`;
export const SET_OFFER_REVIEWS = `SET_OFFER_REVIEWS`;

export const CHANGE_NEAR_OFFERS_STATUS = `CHANGE_NEAR_OFFERS_STATUS`;
export const SET_NEAR_OFFERS = `SET_NEAR_OFFERS`;

export const SET_FAVORITES_OFFERS = `SET_FAVORITES_OFFERS`;
